// <auto-generated />
using System;
using DKaiza.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DKaiza.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261007044847_SincronizarModelo")]
    partial class SincronizarModelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DKaiza.Web.Dominio.CategoriaServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("bytea");

                    b.Property<string>("ImagenTipo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("UsuarioModificaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CategoriasServicio", (string)null);
                });

            modelBuilder.Entity("DKaiza.Web.Dominio.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("EstilistaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("EstilistaId", "Inicio");

                    b.ToTable("Citas", (string)null);
                });

            modelBuilder.Entity("DKaiza.Web.Dominio.Estilista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly?>("FinDescanso")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("FinJornada")
                        .HasColumnType("time without time zone");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea");

                    b.Property<string>("FotoTipo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeOnly?>("InicioDescanso")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("InicioJornada")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("UsuarioModificaId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioRegistroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Estilistas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellidos = "González",
                            Dni = "70000001",
                            Especialidad = "Coloración",
                            FechaRegistro = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinDescanso = new TimeOnly(15, 0, 0),
                            FinJornada = new TimeOnly(21, 0, 0),
                            InicioDescanso = new TimeOnly(13, 0, 0),
                            InicioJornada = new TimeOnly(9, 30, 0),
                            Nombres = "María",
                            Telefono = "999000001"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellidos = "Fernández",
                            Dni = "70000002",
                            Especialidad = "Cabello",
                            FechaRegistro = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinDescanso = new TimeOnly(15, 0, 0),
                            FinJornada = new TimeOnly(21, 0, 0),
                            InicioDescanso = new TimeOnly(13, 0, 0),
                            InicioJornada = new TimeOnly(9, 30, 0),
                            Nombres = "Laura",
                            Telefono = "999000002"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apellidos = "Rojas",
                            Dni = "70000003",
                            Especialidad = "Tratamientos",
                            FechaRegistro = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            FinDescanso = new TimeOnly(15, 0, 0),
                            FinJornada = new TimeOnly(21, 0, 0),
                            InicioDescanso = new TimeOnly(13, 0, 0),
                            InicioJornada = new TimeOnly(9, 30, 0),
                            Nombres = "Carolina",
                            Telefono = "999000003"
                        });
                });

            modelBuilder.Entity("DKaiza.Web.Dominio.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("bytea");

                    b.Property<string>("ImagenTipo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("UsuarioModificaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Servicios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Servicios_Duracion", "\"DuracionMinutos\" > 0");

                            t.HasCheckConstraint("CK_Servicios_Precio", "\"Precio\" > 0");
                        });
                });

            modelBuilder.Entity("DKaiza.Web.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("EstilistaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("EstilistaId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("DKaiza.Web.Dominio.Cita", b =>
                {
                    b.HasOne("DKaiza.Web.Models.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DKaiza.Web.Dominio.Estilista", "Estilista")
                        .WithMany()
                        .HasForeignKey("EstilistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DKaiza.Web.Dominio.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estilista");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("DKaiza.Web.Dominio.Servicio", b =>
                {
                    b.HasOne("DKaiza.Web.Dominio.CategoriaServicio", "Categoria")
                        .WithMany("Servicios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("DKaiza.Web.Models.Usuario", b =>
                {
                    b.HasOne("DKaiza.Web.Dominio.Estilista", null)
                        .WithMany()
                        .HasForeignKey("EstilistaId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DKaiza.Web.Dominio.CategoriaServicio", b =>
                {
                    b.Navigation("Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
